version: '4.38'

services:
  dm_db:
    image: postgres:17
    container_name: currency_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - dm_db
    env_file:
      - .env
    command: >
      sh -c "
      alembic upgrade head &&
      python -m src.insert_data_db &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data: