services:
  dm_db:
    image: postgres:17
    container_name: currency_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      dm_db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c "
      alembic upgrade head &&
      python -m src.insert_data_db &&
      uvicorn main:app --host 0.0.0.0 --port 8080
      "

  frontend:
    image: nginx:latest
    container_name: frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: