"""Add models

Revision ID: 089de2791384
Revises: 
Create Date: 2025-03-25 22:16:25.866279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089de2791384'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('sign', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.create_index(op.f('ix_currency_name'), 'currency', ['name'], unique=True)
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.Column('target_currency_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_currency_id'], ['currency.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency_id', 'target_currency_id', name='unique_currency_rate')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rate')
    op.drop_index(op.f('ix_currency_name'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
